// Shared design-system component library (DESIGN-SYSTEM.md §5).
export { Icon } from './Icon/Icon'
export { Spinner } from './Spinner/Spinner'
export { Button } from './Button/Button'
export type { ButtonProps, ButtonVariant, ButtonSize } from './Button/Button'
export { Badge } from './Badge/Badge'
export type { BadgeProps, BadgeVariant } from './Badge/Badge'
export { STATUS_VARIANTS, statusVariant } from './Badge/statusVariant'
export { Avatar } from './Avatar/Avatar'

export { FieldShell } from './Field/FieldShell'
export { TextField } from './Field/TextField'
export { TextareaField } from './Field/TextareaField'
export { SelectField } from './Field/SelectField'
export type { SelectOption } from './Field/SelectField'
export { Checkbox } from './Field/Checkbox'
export { RadioGroup } from './Field/RadioGroup'
export { Toggle } from './Field/Toggle'
export { FileField } from './Field/FileField'

export { Card, KpiPanel } from './Card/Card'
export { Tabs } from './Tabs/Tabs'
export type { TabItem } from './Tabs/Tabs'
export { Breadcrumbs } from './Breadcrumbs/Breadcrumbs'
export type { Crumb } from './Breadcrumbs/Breadcrumbs'
export { DataTable } from './DataTable/DataTable'
export type { Column, SortState, PaginationState } from './DataTable/DataTable'

export { Menu } from './Menu/Menu'
export type { MenuAction } from './Menu/Menu'
export { Modal } from './Modal/Modal'
export { ConfirmDialog } from './Modal/ConfirmDialog'
export { ToastProvider, useToast } from './Toast/ToastProvider'
export type { ToastVariant } from './Toast/ToastProvider'

export { SideNav } from './SideNav/SideNav'
export type { NavItem, NavSection } from './SideNav/SideNav'
export { TopBar } from './TopBar/TopBar'
